services:
  benchmarker:
    image: 366366/mongodb-benchmarker:mongodb-benchmarker
    volumes:
      - './operations.json:/app/operations.json'
      - './operations.log:/app/operations.log'
    environment:
      BENCHMARK_CONNECTION_STRING: "mongodb://root:secret123@mongo-node-1:27017/test?authSource=admin"
      BENCHMARK_DATABASE_NAME: "test"
      BENCMARK_COLLECTION_NAME: "users"  
