name: Benchmarking Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Initialize MongoDB
      run: docker run -d --network host --name mongodb -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=secret -p 27017:27017 mongo
    - name: Run Application
      env:
        BENCHMARK_CONNECTION_STRING: "mongodb://root:secret@localhost:27017/test?authSource=admin"
        BENCHMARK_DATABASE_NAME: "test"
        BENCHMARK_COLLECTION_NAME: "users"
        BENCHMARK_CONFIG_PATH: "/home/runner/work/MongoDBBenchmarker/MongoDBBenchmarker/"
      run: dotnet run --config


